### ISSUE TITLE
polar chart

### ISSUE THREAD

**Issue by emm888** [miloschuman/yii-highcharts#14]
hi  Milo,
I try to run polar chart, but it's shown as regular chart :(
Any suggestion?

<?php	echo Highcharts::widget([
	'scripts' => [
        'modules/exporting',
        'themes/grid-light',
    ],
   'options' => [
   'chart' => ['polar'=>true, 'type'=>'column'],
              
      'title' => ['text' => 'Fruit Consumption'],
     
      'xAxis' => [
      
     'categories'=> ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        
      ],
      
      'series' => [
         [ 'name' => 'Jane', 'data' =>  [29.9, 71.5, 106.4, 129.2, 144.0, 
         176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]],
        
      ]
   ]
]);
    ?>

**Comment by miloschuman** [comment]
Hi, @emm888. It looks like you are using yii**2**-highcharts, but you have posted in  the yii-highcharts repo. No worries. Please repost your question [there](https://github.com/miloschuman/yii2-highcharts/issues), and I will have an answer for you immediately.

**Comment by miloschuman** [comment]
Answered in miloschuman/yii2-highcharts#16.
