### ISSUE TITLE
Add Click event to Chart body

### ISSUE THREAD

**Issue by ajoudeh** [miloschuman/yii-highcharts#15]
Dears,

how i can add URL to chart body??

Thanks,

**Comment by miloschuman** [comment]
To add a url to individual points on the chart, you can include the urls in the data array. For instance:
```php
$data = array(
    array('x' => 8, 'y' => 67, 'url' => 'http://url.com/1'),
    array('x' => 53, 'y' => 09, 'url' => 'http://url.com/2'),
);
```

and in your series configuration:
```php
...
"series" => array(array(
    "data" => $data,
    "cursor" => "pointer",
    "point" => array(
        "events" => array(
            "click" => "js:function(){ location.href = this.options.url; }"
        )
    )
))
...
```

Here's the [official Highcharts documentation](http://api.highcharts.com/highcharts#plotOptions.series.point.events.click) for that, with a working example.

**Comment by ajoudeh** [comment]
Thanks, but i need to add link to hole chart
Not series only is there anyway?


Sent from Samsung Mobile

Milo Schuman <notifications@github.com> wrote:

To add a url to individual points on the chart, you can include the urls in the data array. For instance:

$data = array(
    array('x' => 8, 'y' => 67, 'url' => 'http://url.com/1'),
    array('x' => 53, 'y' => 09, 'url' => 'http://url.com/2'),
);

and in your series configuration:

...
"series" => array(array(
    "data" => $data,
    "cursor" => "pointer",
    "point" => array(
        "events" => array(
            "click" => "js:function(){ location.href = this.options.url; }"
        )
    )
))
...

Here's the official Highcharts documentation<http://api.highcharts.com/highcharts#plotOptions.series.point.events.click> for that, with a working example.

-

**Comment by miloschuman** [comment]
According to [this StackOverflow answer](http://stackoverflow.com/a/16792514), the chart itself also has a click event.

http://api.highcharts.com/highcharts#chart.events.click

So:
```php
...
"chart" => array(
    "events" => array(
        "click" => "js:function(){ location.href = 'http://moo.com'; }"
    )
)
...
```

**Comment by ajoudeh** [comment]
I tried it but I get JavaScript error after click on chart:

[cid:image004.jpg@01D0B9D8.F0FAD7F0]

Code screenshot
[cid:image005.jpg@01D0B9D8.F0FAD7F0]

**Comment by miloschuman** [comment]
@ajoudeh, I can't help you without more information. The code above works without error for me. If Highcharts is throwing an error, they normally include a link in their error message, which you can follow for more info and troubleshooting. Let me know if you are unable to find a solution. I am on vacation, so it may take me a while to respond. Good luck.

**Comment by miloschuman** [comment]
@ajoudeh, sorry, I didn't notice you attempted to attach a screenshot, but it failed to attach. You may have to reply on GitHub directly.

**Comment by ajoudeh** [comment]
I tried it but I get JavaScript error after click on chart:

![p1](https://cloud.githubusercontent.com/assets/1451200/8636870/2e529640-2880-11e5-8b7f-8ce216869d53.jpg)
 

Code screenshot
 
![p2](https://cloud.githubusercontent.com/assets/1451200/8636871/35100dc8-2880-11e5-8956-b1875d06864d.jpg)

**Comment by miloschuman** [comment]
I am still unable to reproduce the error. It looks like there is an error loading your debug toolbar, and perhaps that is causing a ripple effect on subsequent jQuery events. Try fixing the debug toolbar error first (maybe by clearing your browser cookies or even disabling the debug toolbar) and see if you still get the error on click.

**Comment by raniats** [comment]
Hello, 

   i'm trying to insert a horizontal plotline in my chart in the value 0.42, when my range in yAxis is[-1.2,1.6] , with the following code:
               ` 'yAxis' => array(
			'plotLines' => array(
            			'color' => '#FF0000',
            			'width' => 2,
            			'value' => 0.42
        		),
                       'title' => array(
                                'text' => 'Results',
                       ),
		      'allowDecimals' => true,
		      'min' => -1.2,
		      'max' => 1.6,
		
                ),`
   So when i put the plotline code, the chart shows only the axes and the line doesn't show at all. 
   However when i remove only the code about the plotline everything works just fine.

   Is there a chance to let me know what am i doing wrong and how could i solve this problem?

Thank you  in advance,
Rania
