### ISSUE TITLE
How to install this extension?

### ISSUE THREAD

**Issue by fasi1208** [miloschuman/yii-highcharts#19]
I am using `Yii2` and want to use this extension. I have downloaded it but I am not able to use it. i.e. I don't know where to put the files? I can't find `protected/extensions` in my whole project? Can anyone please help me out?

**Comment by miloschuman** [comment]
This extension is for Yii v1.
Please use the Yii v2 version of this extension. https://github.com/miloschuman/yii2-highcharts
